# @package _global_

# default configuration
defaults:
  # model config
  - trainer: default_trainer.yaml
  - model: simple_model.yaml
  - datamodule: mnist_datamodule.yaml
  - callbacks: default_callbacks.yaml
  - logger: mlflow.yaml

  # enable color logging
  # - override hydra/hydra_logging: colorlog
  # - override hydra/job_logging: colorlog

work_dir: ${hydra:runtime.cwd}
data_dir: /data/datasets
log_dir: /data/logs/kristian/runs/${logger.mlflow.experiment_name}/${now:%H-%M-%S}

# use `python main.py debug=true` for easy debugging
# this will run 1 train, val and test loop with only 1 batch
debug: False

gpu_id: "1"

disable_warnings: True

hydra:
  # output paths for hydra logs
  run:
    dir: ${log_dir}

  sweep:
    dir: ${log_dir}
    subdir: ${hydra.job.num}
