# @package _global_

# default configuration
defaults:
    - logger: mlflow.yaml
    - trainer: default_trainer.yaml
    - quantization: null

logger:
    mlflow:
      tags:
        stage: eval

work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/

log_dir: logs/runs/${logger.mlflow.experiment_name}/eval/${now:%H-%M-%S}

disable_warnings: True

hydra:
    # output paths for hydra logs
    run:
        dir: ${log_dir}
    sweep:
        dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
        subdir: ${hydra.job.num}
