# @package _global_

# default configuration
defaults:
  - logger: mlflow.yaml
  - trainer: default_trainer.yaml
  - quantization: null
  - ood: null
  - pruning: null
  - ensemble: null
  - datamodule: null

logger:
  mlflow:
    tags:
      stage: eval

work_dir: ${hydra:runtime.cwd}
# set datadir
data_dir: /data/datasets
# set logdir
log_dir: /data/logs/kristian/runs/${logger.mlflow.experiment_name}/${now:%H-%M-%S}

disable_warnings: True

gpu_id: None

hydra:
  # output paths for hydra logs
  run:
    dir: ${log_dir}
  sweep:
    dir: ${log_dir}
    subdir: ${hydra.job.num}
